
services:

  mongodb:
    image: mongo
    restart: unless-stopped
    logging:
      driver: none
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db

  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    command: npm run dev
    volumes:
      - ./:/usr/src/app
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
      - 9229:9229
    environment:
      - DB_HOST=mongodb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$MONGODB_DOCKER_PORT

      - NODE_LOCAL_PORT=$NODE_LOCAL_PORT
      - NODE_DOCKER_PORT=$NODE_DOCKER_PORT

volumes:
  db: